# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Create release

on:
  push:
    branches: [ "production-custom" ]
  pull_request:
    branches: [ "production-custom" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build project
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r dist.zip dist
    - name: Create release
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          gh release create "dist.zip" \
              --repo="$GITHUB_REPOSITORY" \
              --generate-notes \
              --target="${{ github.sha }}" \
              --latest
